theme: jekyll-theme-minimal
title: Ngupuk Podcast
description: Mengomentari berbagai topik dengan sekelumit pengetahuan dan rasa sok tau yang tinggi.
logo: /logo.jpg
show_downloads: false
category-list: [episode]
google_analytics: UA-146907084-3
author: Ngupuk
